spring.profiles.active=@spring.profiles.active@

application.name=kusumika-sms
server.servlet.context-path=/kusumika-sms
server.port=8080

#Kusumika DB data source details
kusumika.datasource.driverClassName=org.postgresql.Driver
kusumika.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/postgres
kusumika.datasource.username=postgres
kusumika.datasource.password=password
kusumika.datasource.connectionTimeout=60000
kusumika.datasource.minimumIdle=5
kusumika.datasource.leakDetectionThreshold=60000
kusumika.datasource.maximumPoolSize=20
kusumika.datasource.connectionTestQuery=select 1
kusumika.datasource.poolName=Kusumika Connection Pool
